// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtOS0gTmQreI39NajwVr-R3qt_ksg1FE',
    appId: '1:355083285306:web:a97ffa5b7aa5c42a33d603',
    messagingSenderId: '355083285306',
    projectId: 'eff-logistics',
    authDomain: 'eff-logistics.firebaseapp.com',
    storageBucket: 'eff-logistics.appspot.com',
    measurementId: 'G-DKQF6REXBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzfj_d7m9KYVhh0NDsVtiClyTL8m6oYTw',
    appId: '1:355083285306:android:e5252459a3ea70eb33d603',
    messagingSenderId: '355083285306',
    projectId: 'eff-logistics',
    storageBucket: 'eff-logistics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQtfNXl2Umo7DT_94l02x0yWX-nlL1mtA',
    appId: '1:355083285306:ios:8daaac7ca30024d033d603',
    messagingSenderId: '355083285306',
    projectId: 'eff-logistics',
    storageBucket: 'eff-logistics.appspot.com',
    iosBundleId: 'com.eff.erpnextLogisticsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQtfNXl2Umo7DT_94l02x0yWX-nlL1mtA',
    appId: '1:355083285306:ios:8daaac7ca30024d033d603',
    messagingSenderId: '355083285306',
    projectId: 'eff-logistics',
    storageBucket: 'eff-logistics.appspot.com',
    iosBundleId: 'com.eff.erpnextLogisticsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHtOS0gTmQreI39NajwVr-R3qt_ksg1FE',
    appId: '1:355083285306:web:9629c6bc821572af33d603',
    messagingSenderId: '355083285306',
    projectId: 'eff-logistics',
    authDomain: 'eff-logistics.firebaseapp.com',
    storageBucket: 'eff-logistics.appspot.com',
    measurementId: 'G-R2GPJSP02X',
  );

}